GREETINGS = 'Рады Вас приветствовать в нашем интернет магазине'
PICK_CATEGORY = 'Выберите категорию'
PICK_DISCOUNT_PRODUCT = 'Выберите товар'
ADD_TO_CART = 'Добавить в корзину'
DELETE_ORDER = 'Удалить корзину'
PAY_THE_ORDER = 'Оплатить заказ'
