GREETINGS = 'Рады Вас приветствовать в нашем интернет магазине'
PICK_CATEGORY = 'Выберите категорию'
PICK_DISCOUNT_PRODUCT = 'Выберите товар'
ADD_TO_CART = 'Добавить в корзину'
ADD_PRODUCT = 'Увеличить к-во'
DEL_PRODUCT = 'Уменьшить к-во'
